# ===================================================================
# Spring Boot configuration.
## ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 8080

spring:
  application:
    name: Demo project for Azure Text-to-speech

logging:
  level:
     root: INFO

azure:
  cognitive-service:
    api-key: sp2dftyjy5e8xzfj1vcc84f6c94e59a7 #fake api-key
  region: francecentral
  synthesis :
    language : en-US
    voice-name : Microsoft Server Speech Text to Speech Voice (en-US, JennyNeural)
    output-format-for-file : Webm16Khz16BitMonoOpus
    output-format-for-speaker : Raw24Khz16BitMonoPcm
    output-folder : C:/dev/